In [1]:
%load_ext autoreload
%autoreload 2

import os
import torch
import torch.nn as nn
import pytorch_lightning as pl
import lightly
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import normalize
from PIL import Image
import numpy as np
import torchvision

/home/srinitca/anaconda3/envs/lightly/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [16]:
num_workers = 8
batch_size = 1
seed = 1
max_epochs = 20
input_size = 128
num_ftrs = 32

pl.seed_everything(seed)

path_to_data = '/home/srinitca/vlr/project/ARID_Dataset/clips_v1.5'

INFO:pytorch_lightning.utilities.seed:Global seed set to 1


In [17]:
collate_fn = lightly.data.SimCLRCollateFunction(
    input_size=input_size,
    vf_prob=0.5,
    rr_prob=0.5
)

# We create a torchvision transformation for embedding the dataset after 
# training
test_transforms = torchvision.transforms.Compose([
    torchvision.transforms.Resize((input_size, input_size)),
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize(
        mean=lightly.data.collate.imagenet_normalize['mean'],
        std=lightly.data.collate.imagenet_normalize['std'],
    )
])

dataset_train_simclr = lightly.data.LightlyDataset(
    input_dir=path_to_data
)

In [9]:
dataloader_train_simclr = torch.utils.data.DataLoader(
    dataset_train_simclr,
    batch_size=batch_size,
    shuffle=True,
    collate_fn=collate_fn,
    drop_last=True,
    num_workers=num_workers
)

In [10]:
batch = next(iter(dataloader_train_simclr))

In [22]:
print(batch[1])
print(batch[2])

tensor([496])
['Walk/Walk_16_23-096-mp4.png']


In [1]:

from data import iterator_factory as iter_fac
import torch

dataset = "ARID"
batch_size = 4
clip_length = 16
train_frame_interval = 2
data_root = "./dataset/ARID"
config = {}
config['mean'] = [0.43216, 0.394666, 0.37645] 
config['std'] = [0.22803, 0.22145, 0.216989] 
input_conf = config
resume_epoch=0
return_item_subpath=True
iter_seed = 0 #torch.initial_seed() + 100 + max(0, resume_epoch) * 100

train_iter = iter_fac.creat(name=dataset, 
                            batch_size=batch_size, 
                            clip_length=clip_length, 
                            train_interval=train_frame_interval,
                            mean=input_conf['mean'], std=input_conf['std'], 
                            seed=iter_seed, 
                            data_root=data_root,
                            return_item_subpath=True)

/home/srinitca/anaconda3/envs/lightly/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# from data.iterator_factory import ARIDCollateFunction
# import data.video_transforms as transforms


# video_transform=transforms.Compose([
#                                     transforms.RandomScale(make_square=True, aspect_ratio=[0.8, 1./0.8], slen=[224, 288]),
#                                     transforms.RandomCrop((224, 224)), # insert a resize if needed
#                                     transforms.RandomHorizontalFlip(),
#                                     transforms.RandomHLS(vars=[15, 35, 25]),
#                                     transforms.ToTensor(),
#                                     normalize,
#                                 ]
# aridcollate = ARIDCollateFunction()

In [14]:
out = next(iter(train_iter))
print(out[0].shape)
print(out[1])

torch.Size([4, 16, 3, 224, 224])
tensor([7, 5, 6, 9])


In [3]:
print(out[2])

('Turn/Turn_10_19.mp4', 'Run/Run_10_12.mp4', 'Walk/Walk_10_3.mp4', 'Turn/Turn_16_22.mp4')


tensor([ 5,  9, 10,  5])


In [2]:
%load_ext autoreload
%autoreload 2

import torch

dataset = "ARID"
batch_size = 4
clip_length = 16
train_frame_interval = 2
data_root = "./dataset/ARID"
config = {}
config['mean'] = [0.43216, 0.394666, 0.37645] 
config['std'] = [0.22803, 0.22145, 0.216989] 
input_conf = config
resume_epoch=0
return_item_subpath=True
iter_seed = 0 #torch.initial_seed() + 100 + max(0, resume_epoch) * 100


from data.iterator_factory import get_arid
train_dataset = get_arid(name=dataset, 
                         clip_length=clip_length, 
                         train_interval=train_frame_interval,
                         mean=input_conf['mean'], std=input_conf['std'], seed=iter_seed, data_root=data_root,
                         return_item_subpath=True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from data.iterator_factory import ARIDCollateFunction

num_workers = 1
batch_size = 2
input_size = 224

# collate_fn = lightly.data.SimCLRCollateFunction(
#     input_size=input_size,
#     vf_prob=0.5,
#     rr_prob=0.5
# )

collate_fn = ARIDCollateFunction()

dataloader_train_arid = torch.utils.data.DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    collate_fn=collate_fn,
    drop_last=True,
    num_workers=num_workers
)

In [4]:
out = next(iter(dataloader_train_arid))

batch[0][0].shape=torch.Size([16, 3, 224, 224])
batch_size=2
batch[0][0].dtype=torch.float32
0 torch.Size([16, 3, 224, 224])
0 torch.float32
1 torch.Size([16, 3, 224, 224])
1 torch.float32
2 torch.Size([16, 3, 224, 224])
2 torch.float32
3 torch.Size([16, 3, 224, 224])
3 torch.float32
len(transforms)=4
transforms[i].shape=torch.Size([1, 1, 16, 3, 224, 224]), batch[i % batch_size][0].shape=torch.Size([1, 1, 16, 3, 224, 224])
transforms[i].shape=torch.Size([1, 1, 16, 3, 224, 224]), batch[i % batch_size][0].shape=torch.Size([1, 1, 16, 3, 224, 224])
transforms[i].shape=torch.Size([1, 1, 16, 3, 224, 224]), batch[i % batch_size][0].shape=torch.Size([1, 1, 16, 3, 224, 224])
transforms[i].shape=torch.Size([1, 1, 16, 3, 224, 224]), batch[i % batch_size][0].shape=torch.Size([1, 1, 16, 3, 224, 224])
batch[0][0].shape=torch.Size([16, 3, 224, 224])
batch_size=2
batch[0][0].dtype=torch.float32
0 torch.Size([16, 3, 224, 224])
0 torch.float32
1 torch.Size([16, 3, 224, 224])
1 torch.float32
2 torch.Size

In [6]:
print(out[0][0].shape)
print(out[0][1].shape)
print(out[1])
print(out[2])

torch.Size([2, 1, 16, 3, 224, 224])
torch.Size([2, 1, 16, 3, 224, 224])
tensor([7, 8])
['Stand/Stand_6_9.mp4', 'Turn/Turn_11_36.mp4']
